# Default config:
[API]
ListenAddress = "/ip4/172.16.238.10/tcp/1234/http"
#  Timeout = "30s"
#
[Libp2p]
#  ListenAddresses = ["/ip4/0.0.0.0/tcp/0", "/ip6/::/tcp/0"]
#  ConnMgrLow = 150
#  ConnMgrHigh = 180
#  ConnMgrGrace = "20s"
#
[Metrics]
#  Nickname = ""
#  HeadNotifs = false
#  PubsubTracing = false
#